[package]
name = "sprite-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
png = "0.17.13"
serde = "1.0.210"
serde_json = { version = "1.0.128", features = ["preserve_order"] }
